M48
; DRILL file {KiCad (6.0.7)} date Mon Aug 29 22:08:20 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-29T22:08:20-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1575
%
G90
G05
T1
X4.2944Y-4.9045
X4.2944Y-5.0955
T2
X4.1751Y-4.8927
X4.1751Y-5.1073
T3
X4.26Y-4.24
X4.26Y-5.74
X6.7Y-5.0
T0
M30
